export const techLogoMap = {
  React: '/softwarelogo/react-js-icon.svg',
  'Node.js': '/softwarelogo/node-js-icon.svg',
  'Express.js': '/softwarelogo/Express.svg',
  Express: '/softwarelogo/Express.svg',
  NestJS: '/softwarelogo/Nest.js.svg',
  'Nest.js': '/softwarelogo/Nest.js.svg',
  'Socket.IO': '/softwarelogo/Socket.io.svg',
  'Socket.io': '/softwarelogo/Socket.io.svg',
  BullMQ: '/softwarelogo/BullMQ.png',
  Redis: '/softwarelogo/Redis.svg',
  Prisma: '/softwarelogo/prisma.jpg',
  Render: '/softwarelogo/render.png',
  Keras: '/softwarelogo/Keras.svg',
  Anaconda: '/softwarelogo/Anaconda.svg',
  Tailwind: '/softwarelogo/tailwind-css-icon.svg',
  'Tailwind CSS': '/softwarelogo/tailwind-css-icon.svg',
  'Next.js': '/softwarelogo/nextjs.svg',
  Flutter: '/softwarelogo/flutter-icon.svg',
  Firebase: '/softwarelogo/google-firebase-icon.svg',
  MongoDB: '/softwarelogo/MongoDB.svg',
  'MongoDB Atlas': '/softwarelogo/MongoDB.svg',
  Supabase: '/softwarelogo/supabase-icon.svg',
  CockroachDB: '/softwarelogo/cockroachdblabs.png',
  PostgreSQL: '/softwarelogo/PostgresSQL.svg',
  Postgres: '/softwarelogo/PostgresSQL.svg',
  PostgresSQL: '/softwarelogo/PostgresSQL.svg',
  MySQL: '/softwarelogo/mysql-icon.svg',
  'MySQL Workbench': '/softwarelogo/mysqlworkbench_93532.webp',
  SQLite: '/softwarelogo/sqlite-icon.svg',
  Vite: '/softwarelogo/Vite.js.svg',
  'Vite.js': '/softwarelogo/Vite.js.svg',
  Freelancer: '/freelancer.svg',
  Freelance: '/freelancer.svg',
  Java: '/softwarelogo/java-programming-language-icon.svg',
  Python: '/softwarelogo/python-programming-language-icon.svg',
  'C/C++': '/softwarelogo/c-plus-plus-programming-language-icon.svg',
  C: '/softwarelogo/c-program-icon.svg',
  'C++': '/softwarelogo/c-plus-plus-programming-language-icon.svg',
  JavaScript: '/softwarelogo/javascript-programming-language-icon.svg',
  HTML: '/softwarelogo/html-icon.svg',
  CSS: '/softwarelogo/css-icon.svg',
  TypeScript: '/softwarelogo/typescript-programming-language-icon.svg',
  GDScript: '/softwarelogo/gdscript-icon.svg',
  Dart: '/softwarelogo/dart-programming-language-icon.svg',
  PHP: '/softwarelogo/php-programming-language-icon.svg',
  Kotlin: '/softwarelogo/kotlin-programming-language-icon.svg',
  Laravel: '/softwarelogo/laravel-icon.svg',
  Symfony: '/softwarelogo/symfony-icon.svg',
  Electron: '/softwarelogo/electron.svg',
  'Android Studio': '/softwarelogo/android-studio-icon.svg',
  Android: '/softwarelogo/Android.svg',
  'Android SDK': '/softwarelogo/Android.svg',
  'Accessibility Service': '/softwarelogo/Android.svg',
  BLE: '/softwarelogo/bluetooth-icon.svg',
  'Bluetooth Low Energy': '/softwarelogo/bluetooth-icon.svg',
  Gradle: '/softwarelogo/gradle-icon.svg',
  Godot: '/softwarelogo/godot-game-engine-icon.svg',
  Git: '/softwarelogo/git-icon.svg',
  GitHub: '/softwarelogo/github-icon.svg',
  'VS Code': '/softwarelogo/visual-studio-code-icon.svg',
  CLion: '/softwarelogo/CLion.svg',
  'Technical SEO': '/softwarelogo/seo-icon.svg',
  SEO: '/softwarelogo/seo-icon.svg',
  Vercel: '/softwarelogo/vercel-v0-icon.svg',
  XAMPP: '/softwarelogo/xampp-icon.svg',
  PyCharm: '/softwarelogo/pycharm-icon.svg',
  PyPI: '/softwarelogo/pypi-icon.svg',
  Blender: '/softwarelogo/blender-icon.svg',
  'IntelliJ IDEA': '/softwarelogo/intellij-idea-ide-icon.svg',
  Mkarchi: '/softwarelogo/mkarchi-desktop.svg',
  'Mkarchi Desktop': '/softwarelogo/mkarchi-desktop.svg',
  'Mkarchi CLI': '/softwarelogo/mkarchi-desktop.svg',
  Swing: '/softwarelogo/java-programming-language-icon.svg',
  JDBC: '/softwarelogo/mysql-icon.svg',
  'REST APIs': '/softwarelogo/node-js-icon.svg',
};

export const getTechLogo = (tech) => techLogoMap[tech] || null;
